# Generated by Django 3.0.4 on 2020-03-24 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import short_text_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Depan', models.CharField(default='', max_length=40)),
                ('Nama_Belakang', models.CharField(default='', max_length=40)),
                ('Alamat_Email', models.EmailField(max_length=254)),
                ('Tanggal_Lahir', models.DateField(default='', help_text='Masukkan dalam format MM/DD/YYYY')),
                ('kota', short_text_field.models.ShortTextField(default='', help_text='Masukkan nama kota dengan benar')),
                ('Jenis_Kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('Nomor_HP', phonenumber_field.modelfields.PhoneNumberField(default='+62', max_length=15, region=None, unique=True)),
                ('Akun_Instagram', models.CharField(default='@', max_length=35)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
