# Generated by Django 3.0.4 on 2020-03-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tipe', models.TextField(choices=[('Cerita Pendek/Novel', 'Cerita Pendek/Novel'), ('Edit/Video Musik', 'Edit/Video Musk'), ('Desain Grafis', 'Desain Grafis'), ('Art/Gambar', 'Art/Gambar')], max_length=100)),
                ('konten', models.TextField()),
                ('Diperbarui_Pada', models.DateTimeField(auto_now=True)),
                ('Dibuat_Pada', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Dipublikasikan')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Dibuat_Pada'],
            },
        ),
    ]
