# Generated by Django 3.0.5 on 2020-07-07 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('judul', models.CharField(max_length=200, unique=True)),
                ('id', models.AutoField(default=None, editable=False, primary_key=True, serialize=False)),
                ('tipe', models.TextField(choices=[('Pemberitahuan/Pengumuman', 'Pemberitahuan/Pengumuman'), ('Cerita Pendek/Novel', 'Cerita Pendek/Novel'), ('Edit/Video Musik', 'Edit/Video Musk'), ('Desain Grafis', 'Desain Grafis'), ('Art/Gambar', 'Art/Gambar')], max_length=100)),
                ('konten', django_summernote.fields.SummernoteTextField(default=None)),
                ('Diperbarui_Pada', models.DateTimeField(auto_now=True)),
                ('Dibuat_Pada', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Dipublikasikan')], default=0)),
                ('author', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Dibuat_Pada'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
