# Generated by Django 3.0.4 on 2020-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200325_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nama',
            field=models.CharField(max_length=80),
        ),
    ]
