# Generated by Django 3.0.5 on 2020-07-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200706_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='konten',
        ),
    ]
