# Generated by Django 3.0.5 on 2020-07-06 10:52

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_konten'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='konten',
            field=django_summernote.fields.SummernoteTextField(default=None),
        ),
    ]
