# Generated by Django 3.0.4 on 2020-03-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200325_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nama',
        ),
    ]
