# Generated by Django 3.0.4 on 2020-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nama',
            field=models.CharField(default='', max_length=30),
        ),
    ]
