# Generated by Django 3.0.4 on 2020-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipe',
            field=models.TextField(choices=[('Cerita Pendek/Novel', 'Cerita Pendek/Novel'), ('Edit/Video Musik', 'Edit/Video Musk'), ('Desain Grafis', 'Desain Grafis'), ('Art/Gambar', 'Art/Gambar')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
