# Generated by Django 3.0.4 on 2020-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_tipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
